server:
  port: 8765
  # 开启优雅停机kill -2 可以优雅停机
  shutdown: GRACEFUL
  compression:
    enabled: true
  servlet:
    encoding: # 解决http请求编码问题
      force: true
      charset: UTF-8
      enabled: true
  tomcat:
    uri-encoding: UTF-8 # tomcat编码
    accept-count: 200
    max-connections: 1200
    connection-timeout: 5000
    threads:
      max: 1000
      min-spare: 50
    max-http-form-post-size: 209715200
eureka:
  instance:
    appname: eureka-server
    app-group-name: dev
    lease-renewal-interval-in-seconds: 5 # 设置心跳的时间间隔（默认是30秒）
    lease-expiration-duration-in-seconds: 5 #如果现在超过了5秒的间隔（默认是90秒
    instance-id: ${spring.cloud.client.ip-address}:${server.port} # 在eureka中显示ip和端口
    prefer-ip-address: true # 访问的路径变为 IP 地址
  client:
    fetch-registry: false # 不通过eureka获取注册信息
    register-with-eureka: true # 不注册该服务到eureka上
    service-url:
      # 默认向 http://localhost:8761/eureka 发发请求
#      defaultZone: http://${spring.cloud.client.ip-address}:${server.port}/eureka/
      defaultZone: http://127.0.0.1:${server.port}/eureka/
  server:
    eviction-interval-timer-in-ms: 10000  #及时踢出已关停的节点,间隔时间
    enable-self-preservation: false # 关闭自我保护机制
#spring:
#  security:
#    user:
#      name: yxkong
#      password: 5ycode


