version: '3' #
services:
  mysql:
    container_name: mysql_test
    image: "mysql:5.7"
    # https://hub.docker.com/_/mysql?tab=description
    environment:
      TZ: Asia/Shanghai
      LANG: en_US.UTF-8
      MYSQL_ROOT_PASSWORD: "123456" # root密码
      #      MYSQL_USER: 'yxkong'  # 新增超级用户（直接访问MYSQL_DATABASE）
      #      MYSQL_PASS: '123456'  # 新增超级用户的密码
      MYSQL_DATABASE: demo  # 初始化的数据库名称
    restart: always
    ports:
      - 3307:3306
    volumes:
      - "/etc/localtime:/etc/localtime"
      - "./conf/my.cnf:/etc/mysql/my.cnf"
      - "./data:/var/lib/mysql"
      - "./conf/error.log:/var/log/mysql/error.log"
      - "./init/:/docker-entrypoint-initdb.d/"