server:
  port: 8001

logging:
  config: classpath:log4j2/log4j2-dev.xml
  level:
    root: info
    com.yxkong.demo.infrastructure.persistence.mapper.*: debug

springfox:
  documentation:
    swagger-ui:
      enabled: true
# ===== 自定义swagger配置 ===== #
swagger:
  show: true
  title: ${spring.application.name}
  version: 1.0
  description: '领域驱动demo'
  contactName: 'yxkong'
  contactUrl: 5ycode.com
  contactEmail: 5ycode@sina.com
  serviceUrl: http://localhost:${server.port}

spring:
  redis:
    host: 127.0.0.1
    password: 123456
    port: 3769
    timeout: 3000
    lettuce:
      pool:
        max-active: 10 # 连接池最大连接数（使用负值表示没有限制）
        max-idle: 5 # 连接池中的最大空闲连接
        min-idle: 0 # 连接池中的最小空闲连接
        max-wait: 5000 # 连接池最大阻塞等待时间（使用负值表示没有限制）
  kafka:
    biz:
      enabled: true
    bootstrap-servers: 127.0.0.1:9092
    biz-bootstrap-servers: 127.0.0.1:9082
    consumer:
      group-id: ${spring.application.name}
      enable-auto-commit: true
      auto-commit-interval: 100
      auto-offset-reset: earliest  #latest
      max-poll-records: 100
    producer:
      client-id: ${spring.application.name}
      retries: 3
      batch-size: 1048576
      buffer-memory: 6291456
      acks: all
      compression-type: gzip
    listener:
      concurrency: 1
  sleuth:
    sampler:
      probability: 1.0
  zipkin:
    compression:
      enabled: true
    sender:
      type: kafka
    message-timeout: 60
    service:
      name: ${spring.application.name}

#mysql数据库配置
datasource:
  loan:
    # 使用druid数据源
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/t_db_loan?useUnicode=true&characterEncoding=UTF-8&zeroDateTimeBehavior=convertToNull&serverTimezone=GMT%2B8
    username: root
    password: 123456
    filters: stat
    maxActive: 10
    initialSize: 1
    maxWait: 60000
    minIdle: 1
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 300000
    validationQuery: select 'x'
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    poolPreparedStatements: true
    maxOpenPreparedStatements: 20
  x:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/t_db_x?useUnicode=true&characterEncoding=UTF-8&zeroDateTimeBehavior=convertToNull&serverTimezone=GMT%2B8
    username: root
    password: 123456
    filters: stat
    maxActive: 10
    initialSize: 1
    maxWait: 60000
    minIdle: 1
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 300000
    validationQuery: select 'x'
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    poolPreparedStatements: true
    maxOpenPreparedStatements: 20

eureka:
  server:
    #当Eureka Server节点在短时间内丢失过多的客户端时（可能发送了网络故障），那么这个节点将进入自我保护模式，不再注销任何微服务，当网络故障回复后，该节点会自动退出自我保护模式
    enable-self-preservation: false
    #清理间隔,没有及时下线，利用这个比较好（单位毫秒，默认是60*1000）
    evictionIntervalTimerInMs: 2000
  client:
    #    register-with-eureka: true
    #    fetch-registry: false
    healthcheck:
      #开启健康检查
      enabled: true
    service-url:
      defaultZone: http://127.0.0.1:8765/eureka/
  instance:
    hostname: ${spring.application.name}
    #指定本节点的IP
    #ip-address: 127.0.0.1
    #表示使用IP进行配置
    prefer-ip-address: true
    instance-id: ${spring.cloud.client.ip-address}:${spring.application.name}:${server.port}
    #租期更新时间间隔（默认30秒）
    lease-renewal-interval-in-seconds: 10
    #租期到期时间（默认90秒）
    lease-expiration-duration-in-seconds: 10
    metadata-map:
      user:
        name: yxkong
        password: 5ycode

yxkong:
  id-worker:
    cluster: 127.0.0.1
