server:
  # 开启优雅停机kill -2 可以优雅停机
  shutdown: GRACEFUL
  compression:
    enabled: true
  servlet:
    session:
      timeout: 600
    encoding: # 解决http请求编码问题
      force: true
      charset: UTF-8
      enabled: true
  tomcat:
    uri-encoding: UTF-8 # tomcat编码
    accept-count: 1000
    max-connections: 2000
    connection-timeout: 5000
    threads:
      max: 1000
      min-spare: 10

spring:
  profiles:
    active: dev
  application:
    name: demo
  main:
    allow-bean-definition-overriding: true
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  resources:
    add-mappings: true  #是否开启默认的资源处理，默认为true, 为false swagger不可用
  mvc:
    servlet:
      path: /
  cache:
    type: redis # 配置使用redis
    redis:
      time-to-live: 1800
      cache-expires: #对于redis的key，根据各自的项目情况来定制，不能都一样,失效时间单位秒
        c10s: 10
        c30s: 30
        c1m: 60
        c2m: 60
        c3m: 180
        c5m: 300
        c10m: 600
        c30m: 1800
        c1h: 3600
        c24h: 86400
        c1d: 86400
        c7d: 604800
        c30d: 2592000

# 通过eureka调用都放到这里
eureka:
  instance:
    service:
      quotaService: quota  #额度

mybatis:
  config-location: classpath:mybatis/mybatis-config.xml
  #  mapper-locations: classpath:mybatis/mapper/*/*Mapper.xml
  configuration:
    log-impl: org.apache.ibatis.logging.slf4j.Slf4jLoggerImpl

#健康检查
management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: always
  health:
    status:
      http-mapping: {'UP':200}
    mail:
      enabled: false

feign:
  #开启熔断功能
  hystrix:
    enabled: false
  client:
    config:
      default:
        #loggerLevel: FULL  #fegion的级别,记录所有的日志
        connectTimeout: 2000
        readTimeout: 5000
        loggerLevel: FULL
